import csv
import io
from pathlib import Path

from zeroshield.models import ComparisonReport, ExperimentDefinition

METRIC_ROWS: list[tuple[str, str]] = [
    ("processing_success_rate", "Processing success rate"),
    ("block_rate", "Block rate"),
    ("valid_acceptance_rate", "Valid acceptance rate"),
    ("false_positive_rate", "False positive rate"),
    ("false_negative_rate", "False negative rate"),
    ("parser_reach_rate", "Parser reach rate"),
    ("mean_latency_ms", "Mean latency (ms)"),
    ("log_completeness_rate", "Log completeness rate"),
]

_LATEX_ESCAPES = [
    ("\\", r"\textbackslash{}"),
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
]


def _escape_latex(text: str) -> str:
    for char, replacement in _LATEX_ESCAPES:
        text = text.replace(char, replacement)
    return text


def _metric_rows(report: ComparisonReport) -> list[tuple[str, float, float, float]]:
    rows = []
    for field_name, label in METRIC_ROWS:
        baseline_value = getattr(report.baseline_metrics, field_name)
        mitigation_value = getattr(report.mitigation_metrics, field_name)
        rows.append((label, baseline_value, mitigation_value, mitigation_value - baseline_value))
    return rows


def export_comparison_csv(report: ComparisonReport) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["metric", "baseline", "mitigation", "difference"])
    for label, baseline_value, mitigation_value, difference in _metric_rows(report):
        writer.writerow([label, f"{baseline_value:.6f}", f"{mitigation_value:.6f}", f"{difference:.6f}"])
    return buffer.getvalue()


def export_metrics_tex(report: ComparisonReport) -> str:
    lines = [
        "% Auto-generated by ZeroShield - factual metrics only, do not edit by hand.",
        f"% Experiment: {_escape_latex(report.experiment_id)}",
        r"\begin{tabular}{lrrr}",
        r"\hline",
        r"Metric & Baseline & Mitigation & Difference \\",
        r"\hline",
    ]
    for label, baseline_value, mitigation_value, difference in _metric_rows(report):
        lines.append(
            f"{_escape_latex(label)} & {baseline_value:.3f} & {mitigation_value:.3f} & "
            f"{difference:.3f} \\\\"
        )
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def export_factual_summary_tex(report: ComparisonReport, experiment: ExperimentDefinition) -> str:
    cve_ids = ", ".join(c.cve_id for c in experiment.related_cves)
    baseline_block_pct = report.baseline_metrics.block_rate * 100
    mitigation_block_pct = report.mitigation_metrics.block_rate * 100
    baseline_accept_pct = report.baseline_metrics.valid_acceptance_rate * 100
    mitigation_accept_pct = report.mitigation_metrics.valid_acceptance_rate * 100
    improvement_points = report.block_rate_improvement * 100

    summary = (
        f"In a controlled synthetic ZeroShield experiment ({_escape_latex(report.experiment_id)}, "
        f"{report.total_cases} test cases, dataset derived from {_escape_latex(cve_ids)}), the "
        f"baseline strategy ({_escape_latex(experiment.baseline_strategy)}) blocked "
        f"{baseline_block_pct:.1f}\\% of cases expected to be blocked, while the mitigation "
        f"strategy ({_escape_latex(experiment.mitigation_strategy)}) blocked "
        f"{mitigation_block_pct:.1f}\\% of the same cases (a measured difference of "
        f"{improvement_points:.1f} percentage points). The baseline accepted "
        f"{baseline_accept_pct:.1f}\\% of cases expected to be accepted, and the mitigation "
        f"accepted {mitigation_accept_pct:.1f}\\%. The measured mean-latency overhead of the "
        f"mitigation relative to the baseline was {report.latency_overhead_ms:.3f} ms."
    )

    lines = [
        "% Auto-generated by ZeroShield - factual run outputs only, do not edit by hand.",
        f"% Experiment: {_escape_latex(report.experiment_id)}",
        "",
        summary,
        "",
        r"\textbf{Limitations:}",
        " ".join(_escape_latex(item) for item in report.limitations),
    ]
    return "\n".join(lines) + "\n"


def save_overleaf_export(
    root: Path, report: ComparisonReport, experiment: ExperimentDefinition
) -> Path:
    export_dir = root / report.experiment_id
    export_dir.mkdir(parents=True, exist_ok=True)
    # newline="" required: export_comparison_csv already embeds RFC 4180 \r\n via csv.writer
    (export_dir / "comparison.csv").write_text(
        export_comparison_csv(report), encoding="utf-8", newline=""
    )
    (export_dir / "metrics.tex").write_text(export_metrics_tex(report), encoding="utf-8")
    (export_dir / "factual_summary.tex").write_text(
        export_factual_summary_tex(report, experiment), encoding="utf-8"
    )
    return export_dir
