"""Async run-job tracking, shared between the API (which submits jobs and lets
clients poll them) and the worker process (which consumes jobs from RabbitMQ
and executes them). These are not core SRS-traced domain entities like
ExperimentDefinition/EvidenceManifest - they exist purely as the bookkeeping
side-channel for Milestone 21's asynchronous execution.

JobStore is deliberately a JSON file per job under a directory, not a new
database - consistent with how the rest of ZeroShield treats the filesystem
as the durable, inspectable record (evidence, comparisons, exports all work
the same way).
"""

import os
import uuid
from datetime import datetime
from enum import Enum
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from zeroshield.policies import ExecutionContext

RUN_JOB_QUEUE_NAME = "zeroshield.experiment_runs"


class JobStatus(str, Enum):
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    DENIED = "denied"


class RunJobMessage(BaseModel):
    """The RabbitMQ message payload: only a job_id and enough to look the
    experiment up again - never a filesystem path or strategy identifier.
    `submitted_by_user_id`/`submitted_by_username` (V2 Phase 6) let the
    worker attribute a RUN_DENIED/RUN_FAILED audit event to the real actor
    who submitted the run - both optional so an older, already-queued
    message (or a message from a caller that has no session, which does not
    exist in this application, but keeps the schema forward-compatible)
    still validates."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    job_id: str
    experiment_id: str
    execution_context: ExecutionContext
    submitted_by_user_id: str | None = None
    submitted_by_username: str | None = None


class RunResultSummary(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    baseline_run_id: str
    mitigation_run_id: str
    total_cases: int
    baseline_block_rate: float
    mitigation_block_rate: float
    block_rate_improvement: float
    evidence_location: str


class JobRecord(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    job_id: str
    experiment_id: str
    execution_context: ExecutionContext
    status: JobStatus
    submitted_at: datetime
    updated_at: datetime
    result: RunResultSummary | None = None
    error: str | None = None


class JobStore:
    """File-based job-status side channel. job_id is trusted (server-generated by
    the API, or read back from a message the worker itself published) - callers
    exposing job_id to untrusted input (see api/routes/jobs.py) must validate its
    shape themselves before it ever reaches here."""

    def __init__(self, jobs_dir: Path) -> None:
        self._jobs_dir = jobs_dir

    def _path(self, job_id: str) -> Path:
        return self._jobs_dir / f"{job_id}.json"

    def save(self, record: JobRecord) -> None:
        """Writes via a temp-file-then-atomic-rename (os.replace), never a
        direct write_text() (final release verification fix) - write_text()
        opens in "w" mode, which truncates the file to zero bytes before
        writing a single byte of the new content, and this file is read
        concurrently by a *different process* (the API, polled by clients
        while the worker is mid-save) - a real, reproduced race under the
        live docker-compose stack: GET /jobs/{id} 500'd with a Pydantic
        "EOF while parsing a value" error because it read the file in that
        truncated window. os.replace() is atomic on both POSIX and Windows -
        a concurrent reader always sees either the complete old content or
        the complete new content, never a torn/empty file."""
        self._jobs_dir.mkdir(parents=True, exist_ok=True)
        path = self._path(record.job_id)
        tmp_path = path.with_name(f"{path.name}.{uuid.uuid4().hex}.tmp")
        tmp_path.write_text(record.model_dump_json(indent=2), encoding="utf-8")
        os.replace(tmp_path, path)

    def load(self, job_id: str) -> JobRecord | None:
        path = self._path(job_id)
        if not path.is_file():
            return None
        return JobRecord.model_validate_json(path.read_text(encoding="utf-8"))

    def list_all(self) -> list[JobRecord]:
        """Every job record on disk, most-recently-submitted first - powers
        Mission Control/Runs list pages (V2 Phase 4). Corrupt/unreadable
        files are skipped rather than raised, since this is a best-effort
        listing over a directory of independently-written files, not a
        single authoritative read."""
        if not self._jobs_dir.is_dir():
            return []
        records: list[JobRecord] = []
        for path in self._jobs_dir.glob("*.json"):
            try:
                records.append(JobRecord.model_validate_json(path.read_text(encoding="utf-8")))
            except (OSError, ValueError):
                continue
        return sorted(records, key=lambda r: r.submitted_at, reverse=True)
